sudo: false
cache: node_modules
language: node_js
node_js:
  - "6"
before_install:
  - npm install grunt-cli -g
notifications:
  slack:
    secure: Fg4+Xc6pLJz5YBddhgcMSRecaPNIA1Hwf1Q82QMIgdboEiQubsiwhUC40od+KsuPvCmRtuYRyvde4T4IYVs7QeDG+1O8MRy3BEL2vHdoriU3kP2xTfaEWQMrFcNs7zZtEnNwrEnFbKjSXK7ze22UkTb2pIhHCeY5kJV+bXnPbOjzpqscBdU9IvP1ZTi2u2e+5ImH6F9W328lC3xOK/hKqAp9id8NV9IpXN+xca9297yQ5kHMwBElAkbB/Pv0rjXDm0mBrrotrfWJ5HiZ2yIFbOx9oiHJMF+MjZB8SBP6RcvuMTR8QrYTEHRGsnw6NNZ0gnnaWwFpiCTcGpQ9FHfFcSE7npcthoIGfOrO1Rzsfj2o2PXYDVGkh1Hy1Nuabk6wWl8faDmqLLQhatwvFtvmTONRtc0G8bbQyhDStYckey8BPQ+KnBQxs55q4C6mO15/RGIF7XCpp41H/ckYuJLM1e/oXrs+YHMVKM2F6q5MnIgJNNBu6eh6NXrThly1MRI0QoCGYWas7xDCtb8VTkio4prF/vnYLZb3SxNkiQhdTJd9uqBDT1Q70szN7tvs0XdIgLCIvZjNzplLvqzN/xYbHbTI6fG+Z6wCN4JXP9/X5kTCKukpreCpbC8MHjfN/NHq046gFZmFkjGBnBb6IwO15k787F3776745xfLT6ulsaw=
deploy:
  - provider: npm
    email: "matthew@fxdigital.uk"
    api_key:
      secure: h4MrDgrApdcr5lNqUgpbqBGryVYklC85j8eKFeVESDiHkcL8Ybt/KgBYT7n7tO1E7DReLoEYhYU5hBqPzimyy13FDK6BSd2kvgRJ2My46aNmIQrvRIGMkjjXQIICwTuL00hLrf2qAqyTBMQ/EVT4p2ILzrlWOh2CLNBQeBCxBfQumB1JI+ZR2v/jOKCHCbWpp6qz+HWMauq3f9mDyfUV9Cj4F3t1rU31+XexmRrYjd0PFgGOz/DO69XX2nZEzEw/NSgf3m00Pg0iVzxWllDURDHnebMOBM1biwSTAV6j5YYbB9xKFMHJHdHSOams1GMoHH6bRMK7O3HoNTpd/0W5LBwv3feAazBNUFdvhLbVoXXJiMzDvTlQkRD31xiCxnTGEjDa+oJYat/oiSb75F++v3EMeux7ZcsDuuN5NX1HOEdxqeViisgvlBLbitCslXvYjZc400KCVt4FFjby6Ahl3PmWlosSarYfK2PhrtOWq43Q1Uh9GFW27LjFg3YDs/nCHnMxsSYG0E2yQeAlpw3YMzWRCp2nVRMYKzbeqx6dDkk0URR7rLWJtzAISzxr/use0UU5ySuLereU/kKtKDkqyif/m8o9W+eYw5Yj64LjEk11B0D2Wcox3zDbpITJwvgQikZ0vavT95UTa56aP8BZOKncPYlX0qFhOZBZrC+zZ2M=
    on:
      tags: true
